/**
 * @file badge-definitions.ts
 * @description 뱃지 정의 목록 — 59개 뱃지 시드 데이터
 *
 * 카테고리:
 * - PROFILE: 프로필/온보딩 관련
 * - DIARY: 다이어리 수량
 * - RECORD: 다꾸/기록 (사진 포함)
 * - BOARD: 보드 수집
 * - SPOT: 스팟 탐험
 * - TIME: 시간대/계절
 * - SATISFACTION: 만족도
 * - STREAK: 연속 도전
 * - COMMUNITY: 커뮤니티/가이드
 * - STORY: 예상 못한 스토리 뱃지
 * - LIMITED: 한정/희소
 * - META: 메타 컬렉션 (뱃지 자체를 모으는 행위 보상)
 */

export interface BadgeDefinition {
  key: string;
  nameKo: string;
  descriptionKo: string;
  icon: string;
  category: string;
  isHidden: boolean;
  sortOrder: number;
}

export const BADGE_DEFINITIONS: BadgeDefinition[] = [
  // ─── PROFILE (4개) ────────────────────────────────────────
  {
    key: 'WELCOME',
    nameKo: '첫 항해',
    descriptionKo: '회원가입을 완료했어요',
    icon: '🐋',
    category: 'PROFILE',
    isHidden: false,
    sortOrder: 1,
  },
  {
    key: 'PROFILE_COMPLETE',
    nameKo: '파도의 시작',
    descriptionKo: '서핑 레벨과 보드 타입을 설정했어요',
    icon: '🏄',
    category: 'PROFILE',
    isHidden: false,
    sortOrder: 2,
  },
  {
    key: 'PRO_SURFER',
    nameKo: '프로 서퍼',
    descriptionKo: 'ADVANCED 이상 레벨을 설정했어요',
    icon: '💪',
    category: 'PROFILE',
    isHidden: false,
    sortOrder: 3,
  },
  {
    key: 'DAY_ONE_DIARY',
    nameKo: '가입과 동시에',
    descriptionKo: '가입한 날 바로 첫 다이어리를 작성한 열정 서퍼',
    icon: '🎯',
    category: 'PROFILE',
    isHidden: true,
    sortOrder: 4,
  },

  // ─── DIARY 수량 (3개) ──────────────────────────────────────
  {
    key: 'FIRST_DIARY',
    nameKo: '파도 일지 개설',
    descriptionKo: '첫 번째 다이어리를 작성했어요',
    icon: '📓',
    category: 'DIARY',
    isHidden: false,
    sortOrder: 10,
  },
  {
    key: 'DIARY_10',
    nameKo: '파도 중독',
    descriptionKo: '다이어리를 10개 작성했어요',
    icon: '🌊',
    category: 'DIARY',
    isHidden: false,
    sortOrder: 11,
  },
  {
    key: 'DIARY_50',
    nameKo: '반환점',
    descriptionKo: '다이어리를 50개 작성했어요 (절반의 여정)',
    icon: '🚩',
    category: 'DIARY',
    isHidden: false,
    sortOrder: 12,
  },
  {
    key: 'DIARY_100',
    nameKo: '레전드 서퍼',
    descriptionKo: '다이어리를 100개 작성했어요',
    icon: '🏆',
    category: 'DIARY',
    isHidden: false,
    sortOrder: 13,
  },

  // ─── RECORD 다꾸/기록 (4개) ────────────────────────────────
  {
    key: 'FIRST_PHOTO_DIARY',
    nameKo: '인생샷 헌터',
    descriptionKo: '사진이 포함된 첫 다이어리를 작성했어요',
    icon: '🤳',
    category: 'RECORD',
    isHidden: false,
    sortOrder: 20,
  },
  {
    key: 'PHOTO_DIARY_20',
    nameKo: '다꾸의 권위자',
    descriptionKo: '사진 포함 다이어리를 20개 작성했어요',
    icon: '🎨',
    category: 'RECORD',
    isHidden: false,
    sortOrder: 21,
  },
  {
    key: 'PHOTO_DIARY_50',
    nameKo: '감성 서퍼',
    descriptionKo: '사진 포함 다이어리를 50개 작성했어요',
    icon: '📷',
    category: 'RECORD',
    isHidden: false,
    sortOrder: 22,
  },
  {
    key: 'PHOTO_DIARY_100',
    nameKo: '파도 스타그램',
    descriptionKo: '사진 포함 다이어리를 100개 작성했어요',
    icon: '📱',
    category: 'RECORD',
    isHidden: false,
    sortOrder: 23,
  },
  {
    key: 'LONG_NOVELIST',
    nameKo: '장편 작가',
    descriptionKo: '다이어리 본문을 1000자 이상 작성한 진정한 기록 장인',
    icon: '📜',
    category: 'RECORD',
    isHidden: true,
    sortOrder: 24,
  },

  // ─── BOARD 보드 수집 (4개) ─────────────────────────────────
  {
    key: 'BOARD_3',
    nameKo: '보드 수집 매니아',
    descriptionKo: '3종류 이상의 보드로 서핑 기록을 남겼어요',
    icon: '🛹',
    category: 'BOARD',
    isHidden: false,
    sortOrder: 30,
  },
  {
    key: 'BOARD_5',
    nameKo: '창고 부자',
    descriptionKo: '5종류 이상의 보드로 서핑 기록을 남겼어요',
    icon: '🏠',
    category: 'BOARD',
    isHidden: false,
    sortOrder: 31,
  },
  {
    key: 'BOARD_7',
    nameKo: '보드샵 사장님',
    descriptionKo: '7종류 이상의 보드로 서핑 기록을 남겼어요',
    icon: '🏪',
    category: 'BOARD',
    isHidden: false,
    sortOrder: 32,
  },
  {
    key: 'BOARD_ALL',
    nameKo: '올라운더',
    descriptionKo: '9종류 보드를 모두 경험한 진정한 서퍼',
    icon: '🌀',
    category: 'BOARD',
    isHidden: true,
    sortOrder: 33,
  },

  // ─── SPOT 스팟 탐험 (8개) ──────────────────────────────────
  {
    key: 'FIRST_FAVORITE',
    nameKo: '내 파도',
    descriptionKo: '첫 번째 즐겨찾기 스팟을 추가했어요',
    icon: '⭐',
    category: 'SPOT',
    isHidden: false,
    sortOrder: 40,
  },
  {
    key: 'FAVORITE_10',
    nameKo: '스팟 헌터',
    descriptionKo: '즐겨찾기 스팟을 10개 추가했어요',
    icon: '🗺️',
    category: 'SPOT',
    isHidden: false,
    sortOrder: 41,
  },
  {
    key: 'FAVORITE_20',
    nameKo: '스팟 마스터',
    descriptionKo: '즐겨찾기 스팟을 20개 추가했어요',
    icon: '🏅',
    category: 'SPOT',
    isHidden: false,
    sortOrder: 42,
  },
  {
    key: 'BALI_SURFER',
    nameKo: '발리안',
    descriptionKo: '발리 스팟에서 서핑 기록을 남겼어요',
    icon: '🌴',
    category: 'SPOT',
    isHidden: false,
    sortOrder: 43,
  },
  {
    key: 'KOREAN_SURFER',
    nameKo: '코리안 웨이브',
    descriptionKo: '한국 스팟에서 서핑 기록을 남겼어요',
    icon: '🇰🇷',
    category: 'SPOT',
    isHidden: false,
    sortOrder: 44,
  },
  {
    key: 'TWO_COUNTRIES',
    nameKo: '두 나라 서퍼',
    descriptionKo: '한국과 발리 양쪽에서 서핑 기록을 남겼어요',
    icon: '✈️',
    category: 'SPOT',
    isHidden: false,
    sortOrder: 45,
  },
  {
    key: 'SOMMELIER',
    nameKo: '파도 소믈리에',
    descriptionKo: '5개 이상의 스팟에서 각 3회 이상 서핑했어요',
    icon: '🍷',
    category: 'SPOT',
    isHidden: false,
    sortOrder: 46,
  },
  {
    key: 'SECRET_SPOT',
    nameKo: '나만 아는 스팟',
    descriptionKo: '아직 아무도 기록하지 않은 스팟에 첫 발자국을 남겼어요',
    icon: '🤫',
    category: 'SPOT',
    isHidden: true,
    sortOrder: 47,
  },
  {
    key: 'STUBBORN',
    nameKo: '고집쟁이',
    descriptionKo: '같은 스팟에서 20회 이상 서핑했어요',
    icon: '🪨',
    category: 'SPOT',
    isHidden: false,
    sortOrder: 48,
  },
  {
    key: 'OCEAN_CRUSH',
    nameKo: '바다 짝사랑',
    descriptionKo: '같은 스팟에서 50회 이상 서핑했어요',
    icon: '💙',
    category: 'SPOT',
    isHidden: false,
    sortOrder: 49,
  },
  {
    key: 'FOUR_REGIONS_KOREA',
    nameKo: '한반도 정복자',
    descriptionKo: '동해/남해/서해/제주 4지역 모두에서 서핑한 진정한 탐험가',
    icon: '🗾',
    category: 'SPOT',
    isHidden: true,
    sortOrder: 50,
  },
  {
    key: 'BALI_EXPLORER',
    nameKo: '발리 탐험가',
    descriptionKo: '발리에서 5개 이상의 다른 스팟을 경험했어요',
    icon: '🌴',
    category: 'SPOT',
    isHidden: false,
    sortOrder: 51,
  },
  {
    key: 'ALL_REGIONS_REGULAR',
    nameKo: '전국 단골',
    descriptionKo: '한국 4지역(동/남/서/제주)에서 각 5회 이상 서핑한 단골 서퍼',
    icon: '📌',
    category: 'SPOT',
    isHidden: true,
    sortOrder: 52,
  },

  // ─── TIME 시간대/계절 (6개) ────────────────────────────────
  {
    key: 'DAWN_SURFER',
    nameKo: '새벽 파도',
    descriptionKo: '오전 6시 이전에 서핑한 기록을 남겼어요',
    icon: '🌙',
    category: 'TIME',
    isHidden: true,
    sortOrder: 50,
  },
  {
    key: 'SUNSET_SURFER',
    nameKo: '선셋 서퍼',
    descriptionKo: '오후 6시 이후에 서핑한 기록을 남겼어요',
    icon: '🌅',
    category: 'TIME',
    isHidden: true,
    sortOrder: 51,
  },
  {
    key: 'WINTER_SURFER',
    nameKo: '냉수대',
    descriptionKo: '12~2월 겨울에 서핑 기록을 남겼어요',
    icon: '❄️',
    category: 'TIME',
    isHidden: false,
    sortOrder: 52,
  },
  {
    key: 'WINTER_WARRIOR',
    nameKo: '겨울 바다의 전사',
    descriptionKo: '겨울에 서핑 기록을 5개 이상 남겼어요',
    icon: '🥶',
    category: 'TIME',
    isHidden: false,
    sortOrder: 53,
  },
  {
    key: 'FOUR_SEASONS',
    nameKo: '사계절 서퍼',
    descriptionKo: '봄·여름·가을·겨울 모두 서핑 기록을 남겼어요',
    icon: '🍂',
    category: 'TIME',
    isHidden: false,
    sortOrder: 54,
  },
  {
    key: 'DOUBLE_SESSION',
    nameKo: '오늘도 파도',
    descriptionKo: '하루에 다이어리를 2개 작성했어요',
    icon: '🔄',
    category: 'TIME',
    isHidden: true,
    sortOrder: 55,
  },

  // ─── SATISFACTION 만족도 (5개) ─────────────────────────────
  {
    key: 'PERFECT_DAY',
    nameKo: '완벽한 하루',
    descriptionKo: '만족도 5점 다이어리를 처음 작성했어요',
    icon: '✨',
    category: 'SATISFACTION',
    isHidden: false,
    sortOrder: 60,
  },
  {
    key: 'DEEP_FISH',
    nameKo: '심해어',
    descriptionKo: '만족도 5점 다이어리를 10개 작성했어요',
    icon: '🐠',
    category: 'SATISFACTION',
    isHidden: false,
    sortOrder: 61,
  },
  {
    key: 'WIPEOUT_DAY',
    nameKo: '파도 먹은 날',
    descriptionKo: '만족도 1점 다이어리를 처음 작성했어요',
    icon: '💀',
    category: 'SATISFACTION',
    isHidden: true,
    sortOrder: 62,
  },
  {
    key: 'ROLLERCOASTER',
    nameKo: '롤러코스터',
    descriptionKo: '만족도 1점과 5점 다이어리를 모두 보유하고 있어요',
    icon: '🎢',
    category: 'SATISFACTION',
    isHidden: true,
    sortOrder: 63,
  },
  {
    key: 'TEARS_OF_WAVE',
    nameKo: '눈물의 파도',
    descriptionKo: '만족도 1점 다이어리를 5개 작성했어요',
    icon: '😭',
    category: 'SATISFACTION',
    isHidden: true,
    sortOrder: 64,
  },

  // ─── STREAK 연속 도전 (2개) ────────────────────────────────
  {
    key: 'STREAK_7',
    nameKo: '7일의 파도',
    descriptionKo: '7일 연속으로 다이어리를 작성했어요',
    icon: '🔥',
    category: 'STREAK',
    isHidden: false,
    sortOrder: 70,
  },
  {
    key: 'STREAK_30',
    nameKo: '한 달 서퍼',
    descriptionKo: '30일 연속으로 다이어리를 작성했어요',
    icon: '📅',
    category: 'STREAK',
    isHidden: false,
    sortOrder: 71,
  },
  {
    key: 'STREAK_100',
    nameKo: '백일의 약속',
    descriptionKo: '100일 연속으로 다이어리를 작성한 의지의 서퍼',
    icon: '🔱',
    category: 'STREAK',
    isHidden: false,
    sortOrder: 72,
  },

  // ─── COMMUNITY 커뮤니티/가이드 (4개) ──────────────────────
  {
    key: 'FIRST_VOTE',
    nameKo: '파도 관측자',
    descriptionKo: '컨디션 투표에 처음 참여했어요',
    icon: '👁️',
    category: 'COMMUNITY',
    isHidden: false,
    sortOrder: 80,
  },
  {
    key: 'VOTE_30',
    nameKo: '투표 달인',
    descriptionKo: '컨디션 투표에 30회 참여했어요',
    icon: '👍',
    category: 'COMMUNITY',
    isHidden: false,
    sortOrder: 81,
  },
  {
    key: 'GUIDE_5',
    nameKo: '서핑 교과서',
    descriptionKo: '가이드를 5개 이상 읽었어요',
    icon: '📖',
    category: 'COMMUNITY',
    isHidden: false,
    sortOrder: 82,
  },
  {
    key: 'GUIDE_ALL',
    nameKo: '파도 박사',
    descriptionKo: '가이드를 전부 읽은 서핑 이론가',
    icon: '🎓',
    category: 'COMMUNITY',
    isHidden: false,
    sortOrder: 83,
  },

  // ─── STORY 예상 못한 순간 (10개) ──────────────────────────
  {
    key: 'TIME_CAPSULE',
    nameKo: '파도 타임캡슐',
    descriptionKo: '1년 전 같은 날(±3일) 같은 스팟에서 또 서핑했어요',
    icon: '⏳',
    category: 'STORY',
    isHidden: true,
    sortOrder: 90,
  },
  {
    key: 'FLAT_DAY',
    nameKo: '장판의 날',
    descriptionKo: '파고 0.3m 이하인 날에도 바다를 찾은 진정한 서퍼',
    icon: '🪟',
    category: 'STORY',
    isHidden: true,
    sortOrder: 91,
  },
  {
    key: 'SURF_BUDDY',
    nameKo: '짝꿍 서퍼',
    descriptionKo: '같은 날 같은 스팟에 다른 유저도 다이어리를 작성했어요',
    icon: '👫',
    category: 'STORY',
    isHidden: true,
    sortOrder: 92,
  },
  {
    key: 'SURF_CLASSMATE',
    nameKo: '파도 동창',
    descriptionKo: '같은 유저와 짝꿍 서퍼가 3번 이상 됐어요',
    icon: '🤝',
    category: 'STORY',
    isHidden: true,
    sortOrder: 93,
  },
  {
    key: 'WAVE_WITH_WHALE',
    nameKo: '고래와 함께',
    descriptionKo: '같은 유저와 짝꿍 서퍼가 10번 이상 됐어요',
    icon: '🐋💙',
    category: 'STORY',
    isHidden: true,
    sortOrder: 94,
  },
  {
    key: 'REVENGE_WAVE',
    nameKo: '복수의 파도',
    descriptionKo: '만족도 1점 스팟에 재방문해서 4점 이상을 받았어요',
    icon: '⚔️',
    category: 'STORY',
    isHidden: true,
    sortOrder: 95,
  },
  {
    key: 'REBEL_SURFER',
    nameKo: '역발상 서퍼',
    descriptionKo: '예보 점수 1~2인 날에 만족도 5점을 기록했어요',
    icon: '🙃',
    category: 'STORY',
    isHidden: true,
    sortOrder: 96,
  },
  {
    key: 'CURSED_SURFER',
    nameKo: '포기 모르는 서퍼',
    descriptionKo: '아쉬운 날에도 다음날 같은 스팟에 다시 도전한 끈기 서퍼',
    icon: '👻',
    category: 'STORY',
    isHidden: true,
    sortOrder: 97,
  },
  {
    key: 'WAVE_MASTER',
    nameKo: '파도 장인',
    descriptionKo: '예보 점수 9~10인 날에 만족도 5점을 기록했어요',
    icon: '🧙',
    category: 'STORY',
    isHidden: true,
    sortOrder: 98,
  },
  {
    key: 'NIGHT_OWL',
    nameKo: '밤샘 서퍼',
    descriptionKo: '새벽 1~4시 사이에 다이어리를 작성했어요',
    icon: '🦉',
    category: 'STORY',
    isHidden: true,
    sortOrder: 99,
  },
  {
    key: 'WEEKEND_WARRIOR',
    nameKo: '주말 전사',
    descriptionKo: '4주 연속으로 토/일 다이어리를 작성한 주말 전사',
    icon: '⚔️',
    category: 'STORY',
    isHidden: true,
    sortOrder: 200,
  },
  {
    key: 'MONDAY_SURFER',
    nameKo: '월요 명약',
    descriptionKo: '월요일에 5번 이상 서핑한 월요병 처방전',
    icon: '💊',
    category: 'STORY',
    isHidden: true,
    sortOrder: 201,
  },
  {
    key: 'RAINY_SURFER',
    nameKo: '우중 서퍼',
    descriptionKo: '비 오는 날에도 바다를 찾은 진정한 서퍼',
    icon: '☔',
    category: 'STORY',
    isHidden: true,
    sortOrder: 202,
  },

  // ─── LIMITED 한정/희소 (7개) ───────────────────────────────
  {
    key: 'FOUNDER',
    nameKo: '창립 멤버',
    descriptionKo: '최초 가입 10명 안에 든 전설의 서퍼',
    icon: '👑',
    category: 'LIMITED',
    isHidden: false,
    sortOrder: 100,
  },
  {
    key: 'EARLY_BIRD',
    nameKo: '얼리버드',
    descriptionKo: '최초 가입 100명 안에 든 선구자',
    icon: '🌅',
    category: 'LIMITED',
    isHidden: false,
    sortOrder: 101,
  },
  {
    key: 'FIRST_WAVER',
    nameKo: '퍼스트 웨이버',
    descriptionKo: '특정 스팟에 가장 먼저 다이어리를 남긴 사람',
    icon: '🥇',
    category: 'LIMITED',
    isHidden: false,
    sortOrder: 102,
  },
  {
    key: 'ANNIVERSARY_2026',
    nameKo: '개근상 2026',
    descriptionKo: 'Whale Log 출시 기념일(4월 19일)에 접속했어요',
    icon: '🎂',
    category: 'LIMITED',
    isHidden: false,
    sortOrder: 103,
  },
  {
    key: 'ANNIVERSARY_2027',
    nameKo: '개근상 2027',
    descriptionKo: 'Whale Log 2주년 기념일(4월 19일)에 접속했어요',
    icon: '🎂',
    category: 'LIMITED',
    isHidden: false,
    sortOrder: 104,
  },
  {
    key: 'THREE_COUNTRIES',
    nameKo: '3만ft 서퍼',
    descriptionKo: '한국과 발리 양쪽에서 각각 5개 이상 다이어리를 남겼어요',
    icon: '✈️',
    category: 'LIMITED',
    isHidden: true,
    sortOrder: 105,
  },
  {
    key: 'WILDCARD',
    nameKo: '와일드카드',
    descriptionKo: '운영자가 특별히 수여한 뱃지',
    icon: '🃏',
    category: 'LIMITED',
    isHidden: false,
    sortOrder: 106,
  },
  {
    key: 'ANNIVERSARY_HALF',
    nameKo: '반년 동지',
    descriptionKo: '가입 6개월을 맞이한 든든한 동행자',
    icon: '🎉',
    category: 'LIMITED',
    isHidden: false,
    sortOrder: 107,
  },
  {
    key: 'CHRISTMAS_WAVE',
    nameKo: '크리스마스 파도',
    descriptionKo: '12월 25일 크리스마스에 서핑 기록을 남겼어요',
    icon: '🎄',
    category: 'LIMITED',
    isHidden: true,
    sortOrder: 108,
  },
  {
    key: 'NEW_YEAR_SURF',
    nameKo: '해넘이 서퍼',
    descriptionKo: '1월 1일 새해 첫날에 서핑 기록을 남긴 의지의 서퍼',
    icon: '🌅',
    category: 'LIMITED',
    isHidden: true,
    sortOrder: 109,
  },
  {
    key: 'BIRTHDAY_WAVE',
    nameKo: '생일 파도',
    descriptionKo: '본인 생일에 바다를 찾은 특별한 하루',
    icon: '🎂',
    category: 'LIMITED',
    isHidden: true,
    sortOrder: 110,
  },

  // ─── META 메타 컬렉션 (4개) ───────────────────────────────
  {
    key: 'BADGE_COLLECTOR',
    nameKo: '뱃지 수집가',
    descriptionKo: '뱃지를 30개 이상 모은 컬렉터',
    icon: '🎖️',
    category: 'META',
    isHidden: false,
    sortOrder: 300,
  },
  {
    key: 'BADGE_LEGEND',
    nameKo: '뱃지 전설',
    descriptionKo: '뱃지를 50개 이상 모은 전설의 서퍼',
    icon: '👑',
    category: 'META',
    isHidden: false,
    sortOrder: 301,
  },
  {
    key: 'HIDDEN_HUNTER',
    nameKo: '히든 헌터',
    descriptionKo: '히든 뱃지를 10개 이상 발견한 탐험가',
    icon: '🔍',
    category: 'META',
    isHidden: true,
    sortOrder: 302,
  },
];

/** 앱 출시 기념일 (매년 이 날짜 ±3일 접속 시 해당 연도 ANNIVERSARY 뱃지 지급) */
export const APP_ANNIVERSARY_MONTH = 4; // 4월
export const APP_ANNIVERSARY_DAY = 19;  // 19일
