// 인증 전역 상태 — zustand + expo-secure-store (JWT 토큰 영구 보관)
import { create } from 'zustand';
import { storage } from '../config/storage';

interface User {
  id: string;
  email: string;
  username: string | null;
  avatarUrl: string | null;
  role: string;
  surfLevel: string | null;
  boardType: string | null;
  /** 소셜 로그인 제공자 - 'GOOGLE' | 'KAKAO' | null (일반 가입자) */
  provider?: string | null;
}

interface AuthState {
  user: User | null;
  isAuthenticated: boolean;
  isLoading: boolean;
  /** 구글 신규 가입자 아이디 설정 팝업 노출 여부 — 로그인 직후 true로 설정 */
  showUsernameSetup: boolean;
  initialize: () => Promise<void>;
  /**
   * 로그인 처리
   * @param isNewUser - 소셜 로그인 신규 가입자 여부
   * @param usernameAutoGenerated - username이 시퀀스 fallback으로 부여됐는지 (true면 팝업 노출)
   */
  login: (token: string, user: User, isNewUser?: boolean, usernameAutoGenerated?: boolean) => Promise<void>;
  logout: () => Promise<void>;
  // 프로필 부분 업데이트 (레벨/보드 변경 등)
  updateUser: (partial: Partial<User>) => void;
  /** 아이디 설정 팝업 닫기 — [나중에] 또는 [지금 설정] 클릭 시 호출 */
  dismissUsernameSetup: () => void;
}

export const useAuthStore = create<AuthState>((set) => ({
  user: null,
  isAuthenticated: false,
  isLoading: true,
  showUsernameSetup: false,

  initialize: async () => {
    try {
      const [token, user] = await Promise.all([
        storage.getToken(),
        storage.getUser(),
      ]);
      if (token && user) {
        set({ user, isAuthenticated: true, isLoading: false });
      } else {
        set({ isLoading: false });
      }
    } catch {
      set({ isLoading: false });
    }
  },

  login: async (token: string, user: User, isNewUser?: boolean, usernameAutoGenerated?: boolean) => {
    await Promise.all([
      storage.setToken(token),
      storage.setUser(user),
    ]);
    /**
     * username이 시퀀스 fallback("서퍼N")으로 부여된 경우 팝업 노출.
     * - 구글 가입자: 항상 fallback
     * - 카카오 가입자: 닉네임이 이모지/특수문자뿐이라 sanitize 결과가 비어있는 경우만
     */
    const showSetup = !!usernameAutoGenerated;
    set({ user, isAuthenticated: true, isLoading: false, showUsernameSetup: showSetup });
  },

  logout: async () => {
    await storage.clearAll();
    set({ user: null, isAuthenticated: false, isLoading: false, showUsernameSetup: false });
  },

  updateUser: (partial) => {
    set(s => {
      const updated = s.user ? { ...s.user, ...partial } : s.user;
      /** 변경된 user를 storage에도 반영 */
      if (updated) storage.setUser(updated).catch(() => {});
      return { user: updated };
    });
  },

  dismissUsernameSetup: () => set({ showUsernameSetup: false }),
}));
